## This configuration was generated by terraform-provider-oci

resource oci_database_autonomous_database ajd_mongodb {
  admin_password = var.custom_adb_admin_password
  #are_primary_whitelisted_ips_used = <<Optional value not found in discovery>>
  #autonomous_container_database_id = <<Optional value not found in discovery>>
  #autonomous_database_backup_id = <<Optional value not found in discovery>>
  #autonomous_database_id = <<Optional value not found in discovery>>
  autonomous_maintenance_schedule_type = "REGULAR"
  #clone_type = <<Optional value not found in discovery>>
  compartment_id             = var.compartment_ocid
  cpu_core_count             = "1"
  data_safe_status           = "NOT_REGISTERED"
  data_storage_size_in_gb    = "20"
  data_storage_size_in_tbs   = "1"
  database_management_status = ""
  db_name                    = var.custom_adb_db_name
  db_version                 = "19c"
  db_workload                = "AJD"
  display_name = var.custom_adb_db_name
  freeform_tags = {
  }
  #is_access_control_enabled = <<Optional value not found in discovery>>
  is_auto_scaling_enabled     = "false"
  is_data_guard_enabled       = "false"
  is_dedicated                = "false"
  is_free_tier                = "true"
  is_mtls_connection_required = "false"
  #is_preview_version_with_service_terms_accepted = <<Optional value not found in discovery>>
  #is_refreshable_clone = <<Optional value not found in discovery>>
  #kms_key_id    = "ORACLE_MANAGED_KEY"
  license_model = "LICENSE_INCLUDED"
  nsg_ids = [
  ]
  #ocpu_count = <<Optional value not found in discovery>>
  open_mode                  = "READ_WRITE"
  operations_insights_status = "NOT_ENABLED"
  permission_level           = "UNRESTRICTED"
  #private_endpoint_label = <<Optional value not found in discovery>>
  #refreshable_mode = <<Optional value not found in discovery>>
  #rotate_key_trigger = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_id = <<Optional value not found in discovery>>
  standby_whitelisted_ips = [
  ]
  state = "AVAILABLE"
  #subnet_id = <<Optional value not found in discovery>>
  #switchover_to = <<Optional value not found in discovery>>
  #timestamp = <<Optional value not found in discovery>>
  #vault_id = <<Optional value not found in discovery>>
  whitelisted_ips = [
    "0.0.0.0/0",
  ]
}

